name: UbuPlugin
version: ${project.version}
main: fr.tannoxx.ubuplugin.UbuPlugin
api-version: '1.21'
author: Tannoxx
website: https://ubuearth.fr
description: Plugin professionnel pour UbuEarth SMP avec enchantements customs, système de ranks et outils Earth
load: POSTWORLD
softdepend: [Towny]

commands:
  ubu:
    description: Commande principale du plugin
    usage: /ubu <help|reload|modules>
    aliases: [ubuplugin]
    permission: ubuplugin.command.main

permissions:
  ubuplugin.*:
    description: Toutes les permissions du plugin
    default: op
    children:
      ubuplugin.command.*: true
      ubuplugin.module.*: true
      ubuplugin.admin: true

  ubuplugin.command.*:
    description: Toutes les commandes
    default: op
    children:
      ubuplugin.command.main: true
      ubuplugin.command.reload: true
      ubuplugin.command.help: true

  ubuplugin.command.main:
    description: Utiliser la commande principale
    default: true

  ubuplugin.command.reload:
    description: Recharger la configuration
    default: op

  ubuplugin.command.help:
    description: Afficher l'aide
    default: true

  ubuplugin.module.*:
    description: Accès à tous les modules
    default: op
    children:
      ubuplugin.module.enchants: true
      ubuplugin.module.ranks: true
      ubuplugin.module.earthtools: true
      ubuplugin.module.lobbychat: true
      ubuplugin.module.anvil: true

  ubuplugin.admin:
    description: Accès administrateur complet
    default: op